default:
  app:
    name: Building MQTT API
    version: 1.0.0

  broker:
    mqtt:
      url: mqtt://test.mosquitto.org
      topics: ["unitBalanceResponder"]
      qos:
      protocol: mqtt
      retain:
      subscribe: true

development:

test:

staging:

production:
